import { parseAbi } from 'viem';

export const oneDrawAbi = parseAbi([
  'function nextPoolId() view returns (uint256)',
  'function getPool(uint256 poolId) view returns ((uint256 id,address token,uint128 prizeAmount,uint128 ticketPrice,uint32 capacity,uint32 ticketsSold,uint64 duration,uint64 startTime,uint64 deadline,uint128 protocolFee,uint8 status,address winner,uint32 winningTicket,uint256 randomnessRequestId))',
  'function getEffectiveStatus(uint256 poolId) view returns (uint8)',
  'function getUserTickets(uint256 poolId,address wallet) view returns (uint32[])',
  'function getRefundableAmount(uint256 poolId,address wallet) view returns (uint256)',
  'function getContribution(uint256 poolId,address wallet) view returns (uint256)',
  'function getTicketOwner(uint256 poolId,uint32 ticketIndex) view returns (address)',
  'function buyTickets(uint256 poolId,uint32 quantity)',
  'function claimRefund(uint256 poolId)',
  'function claimPrize(uint256 poolId)',
  'function getClaimablePrize(uint256 poolId,address wallet) view returns (uint256)',
  'function prizeClaimed(uint256 poolId) view returns (bool)',
  'function poolTemplateId(uint256 poolId) view returns (uint256)',
  'function successorPoolId(uint256 poolId) view returns (uint256)',
  'error PoolExpired()',
  'error PoolSoldOut()',
  'error PoolNotOpen()',
  'error InsufficientRemainingTickets()',
  'error RefundUnavailable()',
  'error PrizeUnavailable()',
  'event PoolCreated(uint256 indexed poolId,address indexed token,uint128 prizeAmount,uint128 ticketPrice,uint32 capacity,uint64 duration,uint128 protocolFee)',
  'event PoolStarted(uint256 indexed poolId,uint64 startTime,uint64 deadline)',
  'event TicketsPurchased(uint256 indexed poolId,address indexed buyer,uint32 quantity,uint32 firstTicketIndex,uint256 amount)',
  'event PoolFilled(uint256 indexed poolId,uint32 ticketsSold)',
  'event RandomnessRequested(uint256 indexed poolId,uint256 indexed requestId,address indexed provider)',
  'event WinnerSelected(uint256 indexed poolId,address indexed winner,uint32 winningTicket,uint256 randomValue)',
  'event PrizePaid(uint256 indexed poolId,address indexed winner,uint256 amount)',
  'event ProtocolFeeAccrued(uint256 indexed poolId,address indexed feeVault,uint256 amount)',
  'event RefundClaimed(uint256 indexed poolId,address indexed wallet,uint256 amount)',
  'event PoolTemplateCreated(uint256 indexed templateId,uint128 prizeAmount,uint128 ticketPrice,uint32 capacity,uint64 duration,uint128 protocolFee)',
  'event PoolTemplateStatusUpdated(uint256 indexed templateId,bool enabled)',
  'event PoolRolledOver(uint256 indexed previousPoolId,uint256 indexed nextPoolId,uint256 indexed templateId)',
]);
